plugins {
   id 'java'
   id 'application'
   id 'org.ajoberstar.git-publish' version '4.2.0'
}

repositories {
    mavenCentral()
}


java {
    sourceCompatibility = JavaVersion.toVersion(11)
    targetCompatibility = JavaVersion.toVersion(11)
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.7.0'
    testImplementation 'org.hamcrest:hamcrest-library:2.2'

    // Added test dependencies for JUnit
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(Test) {
    useJUnitPlatform()
    ignoreFailures = true
    testLogging {
        events "passed", "skipped", "failed"
        }
}
// Task to copy custom HTML into reports/
tasks.register('copyHtml', Copy) {
	from 'src/main/html'
	into 'build/reports'
} 

// Task to copy JavaDoc into reports/
tasks.register('copyJavaDoc', Copy) {
	dependsOn tasks.named('javadoc')
	from 'build/docs/javadoc'
	into 'build/reports/reports/javadoc'
}

// Main reports task
task reports(dependsOn: ['build', 'test', 'copyHtml', 'copyJavaDoc']){
}

// Define the location for the temporary working tree
def pagesDir = file("${project.rootDir}/build/website-temp").absolutePath

// Prepare the worktree
tasks.register('clearPages', Delete) {
    delete pagesDir
}

tasks.register('workTreeAdd', Exec) {
    dependsOn 'clearPages'
    workingDir = '.'
    commandLine = ['git', 'worktree', 'add', '-f', pagesDir, 'gh-pages']
}

tasks.register('workTreeCheckout', Exec) {
    dependsOn 'workTreeAdd'
    workingDir = pagesDir
    commandLine = ['git', 'checkout', 'gh-pages']
}

tasks.register('workTree', Exec) {
    dependsOn 'workTreeCheckout'
    workingDir = pagesDir
    commandLine = ['git', 'pull']
}

// Copy files into the worktree
tasks.register('copyReports', Copy) {
    dependsOn 'reports', 'workTree'
    // Copy the main web files
    from('build/reports') {
	exclude 'reports'
    }
    // Copy the generated report folder
    from('build/reports/reports') {
	into 'reports'
    }
    // Pull the unit test reports
    from('build/reports/tests') {
	into 'reports/tests'
    }
    into pagesDir
}

tasks.register('copyWebsite', Copy) {
    dependsOn 'copyReports'
    from file('src/main/html')
    into pagesDir
}

// Stage and commit changes to the gh-pages branch
tasks.register('stageWebsite', Exec) {
    dependsOn 'copyWebsite'
    workingDir = pagesDir
    commandLine = ['git', 'add', '--all', '.']
    ignoreExitValue = true
}

tasks.register('commitWebsite', Exec) {
    dependsOn 'stageWebsite'
    
    // Generates a current timestamp for the commit message
    def timestamp = new Date().format("yyyy-MM-dd HH:mm:ss")

    workingDir = pagesDir
    commandLine = ['git', 'commit', '-m', "Updating webpages at ${timestamp}"]
    ignoreExitValue = true
}

// Push the changes up to GitHub
tasks.register('pushWebsite', Exec) {
    dependsOn 'commitWebsite'
    workingDir = pagesDir
    commandLine = ['git', 'push', 'origin', 'gh-pages']
    ignoreExitValue = true
}

// Clean up the workspace
tasks.register('cleanWorkTree', Delete) {
    dependsOn 'pushWebsite'
    delete pagesDir
}

// The target task requested: orchestrates the sequence and prunes the worktree
tasks.register('deployReports', Exec) {
    group = "Reporting"
    description = "Commit and push website changes to GitHub gh-pages branch"
    dependsOn 'cleanWorkTree'
    workingDir = '.'
    commandLine = ['git', 'worktree', 'prune']
}

application { //Allows  ./gradlew run --args=path-to-test-data
    mainClass = 'edu.odu.cs.MostCommonWords'
}



