plugins {
   id 'java'
   id 'application'
   id 'org.ajoberstar.git-publish' version '4.2.0'
}

repositories {
    mavenCentral()
}


java {
    sourceCompatibility = JavaVersion.toVersion(11)
    targetCompatibility = JavaVersion.toVersion(11)
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.7.0'
    testImplementation 'org.hamcrest:hamcrest-library:2.2'

    // Added test dependencies for JUnit
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(Test) {
    useJUnitPlatform()
    ignoreFailures = true
    testLogging {
        events "passed", "skipped", "failed"
        }
}

// Task to copy custom HTML into reports/
tasks.register('copyHtml', Copy) {
	from 'src/main/html'
	into 'build/reports'
} 

// Task to copy JavaDoc into reports/
tasks.register('copyJavaDoc', Copy) {
	dependsOn tasks.named('javadoc')
	from 'build/docs/javadoc'
	into 'build/reports/javadoc'
}

// Main reports task
tasks.register('reports') {
	dependsOn 'build', 'javadoc', 'copyHtml', 'copyJavaDoc'
}

// Configure the built-in git-publish plugin
gitPublish {
    // Set gitHub Repo
    repoUri = 'git@github.com:ODU-CS351-F26/CS351--exercise-documentation--bbows001.git'

    // Location the plugin clones repo temporarily
    repoDir = file("build/gitPublish") 
    branch = 'gh-pages'

    // Grab everything to copy
    contents {
        from 'build/reports'
    }
    commitMessage = "Updating webpages at ${new Date().format('yyyy-MM-dd HH:mm:ss')}"
}

// Ensure tests and reports generate before git-publish gathers the files
tasks.gitPublishCopy.dependsOn tasks.named('reports')

// Deployment task 
tasks.register('deployReports') {
    group = "Reporting"
    description = "Commit and push website changes to GitHub gh-pages branch"
    dependsOn tasks.named('gitPublishPush')
}

application { //Allows  ./gradlew run --args=path-to-test-data
    mainClass = 'edu.odu.cs.MostCommonWords'
}



